insert into public.customers (company,website,country,city,customer_type,priority,stage,product_category,premium_fit,couture_fit,price_status,price_example,import_probability,buyer_value,contact_email,whatsapp,recommended_line,evidence,source_url,notes) values
('Azrakotan','https://azrakotan.com/','土耳其',null,'独立站','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$250','Unverified','Existing lead','azrakotanabiye@gmail.com',null,'Analyze from existing notes','晚礼服，销售收入为$4,217+ / 月，平均价格$250，近期无新品','https://azrakotan.com/','20260720：已发送邮件。
20260713：无法找到一模一样的产品，有类似风格的，
20260706：和现有客户晚礼服匹配度较高，重点来跟进'),
('Sobraneclassics','https://sobraneclassics.com/','土耳其',null,'独立站','B','Imported existing lead','Unclassified',65,60,'Confirmed > US$100','US$170','Unverified','Existing lead',null,'0551 950 01 94','Analyze from existing notes','男装商务，西装套装平均价格$170，其它T-shirt单件服装平均价格$60，产品上新10每月','https://sobraneclassics.com/','20260720：已添加WhatsApp并发送消息。'),
('Verahayy','https://verahayy.com/','土耳其',null,'独立站','A','Imported existing lead','Premium Evening Dress',90,60,'Existing customer data',null,'Unverified','Existing lead','info@verahayy.com',null,'Analyze from existing notes','女装，连衣裙，数量少，销售收入$8,581+ / 月，最低单件$353，有线下门店','https://verahayy.com/','20260720：已发送邮件，但是被退回了。'),
('Bettyandsam','https://bettyandsam.com','土耳其、德国',null,'独立站、电商平台、线下','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$100','Unverified','Existing lead',null,'+90 850 840 0136','Analyze from existing notes','女装，晚礼服，数量多，单价$100-300','https://bettyandsam.com','20260720：已添加whatsAPP并留言；
20260706：和现有客户晚礼服匹配度较高，重点来跟进'),
('Springstore','https://www.springstore.com.tr/','土耳其',null,'独立站、电商平台','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$120','Unverified','Existing lead','info@springstore.com.tr','+90 850 532 71 75','Analyze from existing notes','女装，晚礼服、毕业礼服、订婚礼服，平均单价$120','https://www.springstore.com.tr/','20260720：已发送邮件，并且添加WhatsApp发送消息。
20260706：和现有客户晚礼服匹配度较高，重点来跟进'),
('Lafaba','https://lafaba.com/','土耳其',null,'独立站、电商平台','A','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$50','Unverified','Existing lead','info@lafaba.com','+90 537 065 80 60','Analyze from existing notes','女装，晚礼服、毕业礼服、订婚礼服，单价$50-130','https://lafaba.com/','20260720：已添加whatsAPP并留言；我们产品的价格可能相对对方网站销售价略高；
20260706：和现有客户晚礼服匹配度较高，重点来跟进'),
('Giyimmasali','https://www.giyimmasali.com/en','土耳其',null,'独立站、电商平台','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$129','Unverified','Existing lead','info@giyimmasali.com','+90 850 2202101','Analyze from existing notes','女装，晚礼服为主，有售卖其他款式，平均单价$129','https://www.giyimmasali.com/en','20260720：已添加whatsAPP并留言；
20260706：和现有客户晚礼服匹配度较高，重点来跟进'),
('Laulei','https://laulei.com/','土耳其',null,'独立站、电商平台','A+','Imported existing lead','Premium Evening Dress',90,60,'Confirmed > US$100','US$225','Unverified','Existing lead','info@laulei.com','+90506 251 55 25','Analyze from existing notes','女装，裙子为主其它款式也有卖，平均单价$225，','https://laulei.com/','20260720：已添加whatsAPP并留言；
20260707：和现有客户晚礼服和连衣裙匹配度较高，重点来跟进'),
('Hollylolly','https://www.hollylolly.net/','土耳其',null,'独立站、电商平台','A+','Imported existing lead','Premium Evening Dress',90,60,'Confirmed > US$100','US$100','Unverified','Existing lead','iletisim@hollylolly.net','+90 553 924 55 90','Analyze from existing notes','女装，裙子为主，其它款式也有卖，平均单价$100','https://www.hollylolly.net/','20260720：已添加whatsAPP并留言；WhatsApp已经给系统禁言7天；

20260707：面向年轻女孩的连衣裙系列比较匹配。'),
('1Moda1Tarz','https://1moda1tarz.com/','土耳其',null,'独立站、电商平台','A','Imported existing lead','Premium Evening Dress',90,60,'Below US$100','US$95','Unverified','Existing lead','info@1moda1tarz.com','+90 546 624 26 44','Analyze from existing notes','女装，裙子为主，其它款式也有卖，平均单价$95','https://1moda1tarz.com/','20260720：已添加whatsAPP并留言；WhatsApp已经给系统禁言7天；

20260707：卖的衣服相对杂，也有连衣裙产品'),
('Carmen','https://carmen.com.tr','土耳其',null,'独立站、电商平台、线下','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$150','Unverified','Existing lead','carmen@carmen.com.tr','+90 533 966 33 16','Analyze from existing notes','女装，礼服、婚纱，平均单价$150','https://carmen.com.tr','20260722：已发送邮件
20260707：和现有客户晚礼服匹配度较高，重点来跟进'),
('Shopgizia','https://shopgizia.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,60,'Confirmed > US$100','US$346','Unverified','Existing lead','info@gizia.com',null,'Analyze from existing notes','女装，裙子为主，其它款式也有卖，平均单价$346，上新数量平均每月220','https://shopgizia.com/','20260722：已发送邮件
20260707：价格比较高端，不一定能找到匹配这个价格的货源。'),
('Bysaygi','https://bysaygi.com/','土耳其',null,'独立站、电商平台','A','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$120','Unverified','Existing lead',null,'+90 533 030 77 75','Analyze from existing notes','女装，晚礼服为主，有售卖其他款式，平均单价$120','https://bysaygi.com/','20260722：在独立站里发联系表格联系
20260707：卖的衣服相对杂，也有连衣裙产品'),
('Nocturne','https://www.nocturne.com.tr/','土耳其',null,'独立站、电商平台、线下','A+','Imported existing lead','Premium Evening Dress',90,60,'Below US$100','US$85','Unverified','Existing lead','info@nocturne.com.tr',null,'Analyze from existing notes','女装，裙子、日常款式，裙子平均单价$85-350','https://www.nocturne.com.tr/','20260722：已发送邮件
20260707：和现有客户晚礼服和连衣裙匹配度较高，重点来跟进'),
('Sagaza','https://sagaza.com/en','土耳其',null,'独立站、电商平台、线下','A','Imported existing lead','Premium Evening Dress',90,60,'Confirmed > US$100','US$172','Unverified','Existing lead','order@sagaza.com',null,'Analyze from existing notes','女装，裙子、日常款式，平均单价$172，上新数量平均每月75','https://sagaza.com/en','20260722：已发送邮件，邮件发送失败，在独立站里发联系表格联系
20260707：和现有客户连衣裙匹配度较高，重点来跟进'),
('Thezks','https://thezks.com/','土耳其',null,'独立站、电商平台、线下','A','Imported existing lead','Premium Evening Dress',90,60,'Below US$100','US$50','Unverified','Existing lead','info@thezks.com','+90 555 066 32 04','Analyze from existing notes','女装，裙子，平均单价$50，上新数量平均每月103','https://thezks.com/','20260722：已发送邮件
20260707：价格50美金左右的产品卖得最好，可以跟进。'),
('Rengin','https://rengin.com.tr/en','土耳其',null,'独立站、电商平台、线下','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$250','Unverified','Existing lead',null,'0 212 233 68 71','Analyze from existing notes','女装，礼服、婚纱，平均单价$250','https://rengin.com.tr/en','20260722：在独立站里发联系表格联系
20260707：礼服系列100-200美金，相对成熟女性的服装，可以重点推荐下。'),
('Sericamoda','https://www.sericamoda.com/','土耳其',null,'独立站、电商平台','A','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$90','Unverified','Existing lead','bilgi@sericamoda.com','0554 022 12 13','Analyze from existing notes','女装，晚礼服、裙子，其它款式也有卖，平均单价$90','https://www.sericamoda.com/','20260722：已发送邮件'),
('Anglecreate','https://www.anglecreate.com/','土耳其',null,'独立站、电商平台','A','Imported existing lead','Premium Evening Dress',90,60,'Confirmed > US$100','US$110','Unverified','Existing lead','info@anglecreate.com',null,'Analyze from existing notes','女装，裙子为主，其它款式也有售卖，平均单价$110','https://www.anglecreate.com/','20260723：已发送邮件'),
('Olaabiye','https://www.olaabiye.com/','土耳其',null,'独立站、电商平台','A+','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$127','Unverified','Existing lead','info@olaabiye.com',null,'Analyze from existing notes','女装，礼服，平均单价$127','https://www.olaabiye.com/','20260723：已发送邮件'),
('Trendyol','https://www.trendyol.com/sr?mid=262718&os=1&pi=4','土耳其',null,'电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$149','Unverified','Existing lead',null,'0544 325 72 82','Analyze from existing notes','女装，礼服，平均单价$149','https://www.trendyol.com/sr?mid=262718&os=1&pi=4','202607023：未找到邮箱，WhatsApp被封'),
('En','https://en.abiyefon.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$150','Unverified','Existing lead','destek@abiyefon.com','+90555 011 37 25','Analyze from existing notes','女装，礼服，平均单价$150','https://en.abiyefon.com/','20260723：已发送邮件'),
('Abiyepazari','https://www.abiyepazari.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$110','Unverified','Existing lead','info@abiyepazari.com',null,'Analyze from existing notes','女装，礼服，平均单价$110','https://www.abiyepazari.com/','20260723：已发送邮件'),
('Abiyenial','https://abiyenial.com.tr/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$80','Unverified','Existing lead','support@abiyenial.com','05320681810','Analyze from existing notes','女装，礼服，平均单价$80','https://abiyenial.com.tr/','20260723：已发送邮件，邮件发送失败'),
('Lirenzaabiye','https://www.lirenzaabiye.com/','土耳其',null,'独立站、电商平台、线下','B','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$85','Unverified','Existing lead','missperyy01@gmail.com',null,'Analyze from existing notes','女装，礼服，平均单价$85','https://www.lirenzaabiye.com/','20260723：已发送邮件'),
('Iyemabiye','https://www.iyemabiye.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$128','Unverified','Existing lead','iyemabiye@gmail.com',null,'Analyze from existing notes','女装，礼服，平均单价$128','https://www.iyemabiye.com/','20260723：已发送邮件'),
('Missswans','https://missswans.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$80','Unverified','Existing lead',null,'+90 533 301 59 99','Analyze from existing notes','女装，礼服、婚纱，平均单价$80','https://missswans.com/','20260723：在独立站里发联系表格联系'),
('Bdmexclusive','https://bdmexclusive.com.tr/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$200','Unverified','Existing lead',null,'+90 546 286 75 05','Analyze from existing notes','女装，礼服，平均单价$200','https://bdmexclusive.com.tr/','20260723：在独立站里发联系表格联系'),
('Sarebutik','https://sarebutik.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Below US$100','US$88','Unverified','Existing lead','info@sarebutik.com','0531 434 45 93','Analyze from existing notes','女装，礼服，平均单价$88','https://sarebutik.com/','20260723：已发送邮件'),
('Kaleiciyildizlar','https://kaleiciyildizlar.com/','土耳其',null,'独立站、电商平台','B','Imported existing lead','Premium Evening Dress',90,80,'Confirmed > US$100','US$100','Unverified','Existing lead','Cn_yldz@hotmail.com','542 172 172 22','Analyze from existing notes','女装，礼服，平均单价$100','https://kaleiciyildizlar.com/','20260723：已发送邮件'),
('Kenzel','https://kenzel.com.tr/en/','Turkey','Istanbul','Premium eveningwear retailer with stores','A+','New researched lead','Both',95,88,'Confirmed > US$100','₺13,990–₺28,990','Medium','Very high',null,'+90 505 824 24 24','Minimalist satin, mermaid, pearl and stone-detail evening gowns','Two Nişantaşı stores, online retail, extensive evening/prom range and high price positioning.','https://kenzel.com.tr/en/','Strong match for both product lines; verify external sourcing openness.'),
('Eser Giyim','https://www.esergiyim.com.tr/en/collections/nisantasi-abiye-magazasi','Turkey','Istanbul','Multi-brand premium eveningwear retailer','A+','New researched lead','Both',96,90,'Confirmed > US$100','₺9,995–₺28,990+','High','Very high',null,null,'Both minimalist premium and heavy embellished evening gowns','Carries 500+ eveningwear products from multiple brands, indicating active buying and assortment management.','https://www.esergiyim.com.tr/en/collections/nisantasi-abiye-magazasi','One of the strongest buyer profiles because it is multi-brand rather than a single atelier.'),
('Ragibesa','https://www.ragibesa.com/','Turkey','Istanbul','Luxury designer boutique / DTC','A','New researched lead','Both',88,93,'Confirmed > US$100','₺15,750–₺51,250','Low–Medium','High',null,'+90 530 123 40 76','Sequined, embellished, red-carpet and statement dresses','High-price Nişantaşı eveningwear boutique with sequins, embellishment and red-carpet styles.','https://www.ragibesa.com/','Best approached with special capsule or handwork capacity.'),
('Cercis','https://cercistr.com/en','Turkey','Istanbul','Nişantaşı premium eveningwear brand / retailer','A','New researched lead','Premium Evening Dress',95,84,'Confirmed > US$100','₺16,900 example','Low–Medium','High',null,null,'Clean corset, draped satin and sophisticated minimalist gowns','Dedicated premium eveningwear positioning with modern silhouettes and Nişantaşı retail presence.','https://cercistr.com/en','Excellent minimalist-style fit.'),
('Habone Butik','https://habonebutik.com/','Turkey','Istanbul','Independent modest eveningwear boutique','A','New researched lead','Heavy Hand-beaded Couture',82,91,'Confirmed > US$100','US$152–US$187 example','Medium–High','High','habone.nour@gmail.com','+90 534 215 33 36','Beaded cape gowns and embellished modest formal dresses','Independent Istanbul boutique selling beaded and couture modest evening gowns with international pricing.','https://habonebutik.com/','Strong fit for heavy handwork line, especially modest silhouettes.'),
('MissBony','https://www.missbony.com/MB/pages/eng/aboutus_en.html','Turkey','Izmir','Small-quantity wholesale formalwear supplier','B','New researched lead','Unclassified',70,82,'Wholesale price not public','Not public','Low','Strategic',null,'+359 888 795 391','Custom mother-daughter and special-order formal gowns','Offers small-quantity wholesale and made-to-order formal gowns to boutiques in Europe.','https://www.missbony.com/MB/pages/eng/aboutus_en.html','More likely competitor/partner than buyer; retain as B-level strategic lead.'),
('Nueve Collection','https://nuevecollection.com/','Turkey','Istanbul','Luxury couture retailer/brand','A+','New lead','Heavy Hand-beaded Couture',72,98,'Confirmed > US$100','₺260,500–₺315,000','Medium','Very high','info@nuevecollection.com','+90 538 887 26 06','Heavy hand-beaded / crystal couture gowns','High-ticket crystal and feather evening gowns; direct online sales; made-to-order positioning.','https://nuevecollection.com/crystal-feather-evening-dress/','Top-priority style match for US$100-cost couture products.'),
('B&B Couture','https://bbcouture.com.tr/','Turkey','Istanbul','Luxury designer brand / retail stores','A+','New lead','Heavy Hand-beaded Couture',82,94,'Confirmed > US$100','₺58,000–₺87,000','Low–Medium','High',null,null,'Crystal, mermaid and statement couture gowns','Large eveningwear assortment, Nişantaşı sales points, high retail price positioning.','https://bbcouture.com.tr/en/collections/all','Approach as capacity-extension / special-style supplier, not as a generic factory.'),
('Tiara Haute Couture','https://tiara.com.tr/en','Turkey','Istanbul','Haute couture brand / online retailer','A+','New lead','Both',90,92,'Confirmed > US$100','₺14,999–₺43,999','Medium','High',null,null,'Both premium minimalist and embellished couture','Dedicated guest, graduation, cocktail, engagement and plus-size evening categories.','https://tiara.com.tr/en','Strong two-product-line fit.'),
('Jarden Atelier','https://jardenabiye.com/','Turkey','Istanbul','Contemporary evening atelier / DTC','A','New lead','Premium Evening Dress',94,75,'Confirmed > US$100','₺15,600–₺24,600','Low–Medium','Medium–High',null,null,'Minimalist satin, sculpted and clean evening dresses','Modern limited-edition evening collection with premium pricing and strong minimalist positioning.','https://jardenabiye.com/','Excellent match for US$20–50 cost premium line.'),
('Svaila','https://www.svaila.com/','Turkey',null,'Independent online eveningwear boutique','A+','New lead','Premium Evening Dress',92,78,'Confirmed > US$100','US$205–US$325','Medium–High','High',null,null,'Premium satin, sequin and embellished evening gowns','Independent boutique selling Turkey-made evening gowns for engagements, bridesmaids and events.','https://www.svaila.com/','Ideal boutique profile; investigate ownership, volume and sourcing model.'),
('Mira Couture Official','https://www.miracoutureofficial.com/','Turkey',null,'Shopify luxury dress retailer','A','New lead','Premium Evening Dress',88,78,'Likely > US$100','₺10,000–₺13,000','Medium–High','High',null,null,'Premium evening and occasion dresses','Shopify storefront, luxury-dress positioning, direct-to-consumer product catalog.','https://www.miracoutureofficial.com/','Verify average order value and whether products are self-produced or sourced.'),
('RCT Edit','https://rctedit.com/','Turkey','Istanbul','Curated designer marketplace / wholesale platform','A','New lead','Heavy Hand-beaded Couture',80,92,'Confirmed > US$100','Up to €2,000','Low','Strategic',null,null,'Limited-run couture and made-to-order gowns','Curates Istanbul ateliers and supports both retail and wholesale sourcing.','https://rctedit.com/','Potential channel/partner rather than conventional importer.'),
('Tuba Ergin','https://tubaergin.com/','Turkey','Istanbul','Contemporary designer label','A','New lead','Both',88,86,'Confirmed > US$100','US$850–US$1,550 dresses','Low','Medium',null,null,'High-end sculpted and statement dresses','International DTC designer label with premium evening and maxi-dress pricing.','https://tubaergin.com/','Approach for outsourced capsules, overflow capacity or special embellishment.'),
('Pernotte Fashion','https://www.pernotte.com/','Turkey','Istanbul','Wholesale evening-dress trader','A+','New lead','Premium Evening Dress',90,82,'Wholesale price not public','Luxury evening dresses','High','Very high','pernottefashion@gmail.com','+90 537 988 3572','Both premium and heavy embellished wholesale styles','Laleli wholesale business, broad size range, orders through WhatsApp/Telegram.','https://www.pernotte.com/','Strong trading-company profile; confirm China import openness.'),
('Dekolte Shop','https://dekolteshop.com/en/','Turkey','Istanbul','Wholesale evening-dress supplier / trader','A','New lead','Premium Evening Dress',94,75,'Wholesale price not public','Not public','Medium–High','Very high',null,null,'Fast-moving premium satin, sequin and plus-size dresses','Targets boutiques, retailers and online sellers; regular stock updates and broad eveningwear categories.','https://dekolteshop.com/en/','Potential buyer, competitor or distribution partner; qualification call required.'),
('Polen Poe','https://polenpoe.com/','Turkey','Istanbul','Luxury wholesale brand','A','New lead','Premium Evening Dress',90,84,'Wholesale access required','Not public','Medium','High','online@polenpoe.com',null,'Premium wholesale dresses and selective couture pieces','Wholesale luxury-dress supplier serving boutiques internationally.','https://polenpoe.com/','May be a competitor; still valuable for partnership or production overflow.'),
('World Wide Couture','https://worldwidecouture.com/','Turkey',null,'Multi-designer couture marketplace','A','New lead','Heavy Hand-beaded Couture',70,97,'Confirmed > US$100','€825–€1,225','Low–Medium','Strategic',null,null,'Heavy hand-beaded couture, red-carpet and pageant gowns','Sells hand-beaded Turkish designer evening gowns at luxury price points.','https://worldwidecouture.com/products/hand-beaded-evening-dress-1','Potential marketplace channel and benchmark account.'),
('Janel Abiye','https://janelabiye.com/','Turkey','Istanbul','Wholesale evening-dress manufacturer/supplier','A','New lead','Premium Evening Dress',88,84,'Wholesale price not public','Not public','Medium','High','janelabiye8@gmail.com','+90 505 473 4399','Premium and embellished wholesale evening dresses','Wholesale-focused evening dress business with showroom and factory in Osmanbey; serves retailers and boutiques worldwide.','https://janelabiye.com/contact-us/','Potential buyer only if open to outsourced styles or overflow production; otherwise strategic channel/competitor.'),
('SETRE','https://www.setre.com/','Turkey','Istanbul','International womenswear brand and wholesaler','A','New lead','Premium Evening Dress',86,68,'Retail price verification needed','Wholesale program public','Medium','Very high',null,null,'Premium minimalist evening and occasion dresses','Established Turkish womenswear house supplying retailers and distributors in 80+ countries; evening dresses are part of its seasonal collections.','https://offer.setre.com/','Strong commercial scale; qualify sourcing model and external supplier openness.'),
('Lacrima','https://www.lacrima.com.tr/','Turkey','Istanbul','Eveningwear brand with retail partner network','A','New lead','Premium Evening Dress',88,82,'Retail price verification needed','Not public','Low–Medium','High',null,null,'Premium evening dresses and selective embellished gowns','Long-established eveningwear company with more than 250 partners in Turkey and over 50 partners in 20+ countries.','https://www.lacrima.com.tr/become-point-of-sale','Likely producer, but scale and distribution network make it relevant for overflow or capsule cooperation.'),
('Istanbul Fashion Center','https://istanbulfashioncenter.com/','Turkey','Istanbul','B2B wholesale marketplace and distributor','A+','New lead','Both',92,88,'Wholesale pricing','4,000+ dress models advertised','High','Very high',null,'+90 552 766 7770','Both premium and heavy embellished lines','Large wholesale platform connecting retailers with Turkish dress manufacturers; supports bulk and smaller test orders and worldwide shipping.','https://istanbulfashioncenter.com/collections/wholesale-evening-dress','Strategic distribution target; pitch curated China-sourced collection with reliable Turkey logistics.'),
('Laryss Sharm','https://sharm.laryss.com/','Turkey','Istanbul','Independent DTC nightwear brand','A+','New lead','Premium Evening Dress',96,65,'Confirmed > US$100','US$125–US$189','Medium–High','High',null,null,'Minimalist satin, corset and slit maxi dresses','Istanbul-designed limited-production brand with worldwide shipping and multiple dresses priced above US$100.','https://sharm.laryss.com/','Excellent fit for US$20–50 cost premium line.'),
('Tiah Atelier','https://www.tiah.com.tr/en/','Turkey','Istanbul','Eveningwear atelier and online retailer','A','New lead','Premium Evening Dress',91,78,'Confirmed > US$100','₺14,750–₺20,250 examples','Low–Medium','High',null,'+90 212 230 1022','Premium evening dresses and selected embellished styles','Operates a 64-product evening dress category and sells through its own online store; products are made in its workshop.','https://www.tiah.com.tr/en/evening-dress','Approach as outsourced capacity or special-style partner rather than generic supplier.'),
('Beyaz Melek Moda','https://www.beyazmelekmoda.com/','Turkey','Istanbul','Luxury bridal and eveningwear atelier','A','New lead','Heavy Hand-beaded Couture',76,91,'Price verification needed','Custom luxury positioning','Low–Medium','Medium–High','beyazmelekmoda@hotmail.com','+90 544 449 08 88','Heavy hand-beaded couture and custom evening gowns','Luxury handmade bridal and evening dresses with custom orders and worldwide shipping from Turkey.','https://www.beyazmelekmoda.com/','Strong couture style match; likely smaller-volume, higher-margin account.'),
('Zeynep Erdoğan Design','https://zeyneperdogan.com/','Turkey','Istanbul','Designer label / online retailer','A','New lead','Heavy Hand-beaded Couture',84,88,'Confirmed > US$100','₺53,500 example','Low','Medium',null,null,'Statement premium and couture evening dresses','Designer label sells high-priced evening dresses and operates pre-order production.','https://zeyneperdogan.com/products/new-shila','Potential capsule or embellishment collaboration; low probability for routine importing.'),
('Miss Diamond','https://www.missdiamond.com.tr/en','Turkey','Istanbul','Eveningwear retailer with physical stores','A+','New lead','Both',90,86,'Price verification needed','Premium positioning','Medium–High','Very high','info@missdiamond.com.tr','+90 552 850 4000','Premium and embellished evening dresses','Nearly 30 years in fashion, two Istanbul stores, online sales, worldwide shipping and a broad evening-glamour positioning.','https://www.missdiamond.com.tr/en/ourshops','Strong retail account profile; verify sourcing and buying contact.'),
('Donna Miranda','https://www.donnamiranda.com.tr/','Turkey','Istanbul','Eveningwear brand / online retailer','A','New lead','Premium Evening Dress',91,72,'Price verification needed','Not public','Medium','High','aerkunt@donnamiranda.com.tr','+90 541 283 6617','Premium satin and contemporary evening dresses','Independent Istanbul eveningwear brand with online ordering, showroom and direct contact details.','https://www.donnamiranda.com.tr/','Good premium-line fit; verify average retail price before outreach.'),
('Lapeni','https://lapeni.com/','Turkey','Istanbul','Modest eveningwear brand / showroom','B','New lead','Unclassified',62,70,'Price verification needed','Not public','Medium','Medium',null,'+90 506 503 6344','Selective embellished modest gowns','Merter-based eveningwear business with showroom, WhatsApp ordering and special-occasion focus.','https://lapeni.com/','Lower style match because modest eveningwear is not the core target; retain as secondary prospect.')
on conflict do nothing;
