export type Customer = {
  id: string;
  company: string;
  website: string | null;
  country: string | null;
  city: string | null;
  customer_type: string | null;
  priority: string;
  stage: string;
  product_category: string;
  premium_fit: number;
  couture_fit: number;
  price_status: string | null;
  price_example: string | null;
  import_probability: string | null;
  buyer_value: string | null;
  contact_email: string | null;
  whatsapp: string | null;
  recommended_line: string | null;
  evidence: string | null;
  source_url: string | null;
  notes: string | null;
  next_follow_up_at: string | null;
  is_excluded: boolean;
  exclusion_reason: string | null;
  excluded_at: string | null;
  owner_id: string | null;
  assigned_by: string | null;
  assigned_at: string | null;
  has_customs_import_records: boolean;
  customs_import_count: number;
  first_customs_import_at: string | null;
  latest_customs_import_at: string | null;
  created_at: string;
  updated_at: string;
};

export type FollowUp = {
  id: string;
  customer_id: string;
  channel: string;
  summary: string;
  outcome: string | null;
  next_action: string | null;
  happened_at: string;
  created_at: string;
  created_by: string | null;
};

export type WhatsAppMessage = {
  id: string;
  meta_message_id: string;
  customer_id: string | null;
  direction: "inbound" | "outbound";
  from_number: string;
  to_number: string;
  contact_name: string | null;
  message_type: string;
  text_body: string | null;
  media_id: string | null;
  media_mime_type: string | null;
  status: string;
  error_text: string | null;
  raw_payload: Record<string, unknown> | null;
  sent_by: string | null;
  happened_at: string;
  created_at: string;
  updated_at: string;
};

export type EmailAccount = {
  id: string;
  user_id: string;
  provider: "google";
  email: string;
  access_token: string;
  refresh_token: string | null;
  expires_at: string | null;
  scopes: string | null;
  created_at: string;
  updated_at: string;
};
