import type { LeadCandidate } from "./types";

// Demonstration data keeps the MVP usable before a paid search provider is selected.
// Replace this adapter with a web/search API connector without changing scoring or CRM.
export const demoCandidates: LeadCandidate[] = [
  {
    id: "demo-1",
    company: "Maison Bosphorus",
    website: "https://demo.example/maison-bosphorus",
    country: "Turkey",
    city: "Istanbul",
    customerType: "Multi-brand Luxury Boutique",
    description: "Luxury occasion-wear retailer with two Istanbul showrooms and an international designer edit.",
    sourceUrl: "https://demo.example/source/maison-bosphorus",
    signals: ["importer", "multi_brand", "premium_positioning", "evening_dress_focus", "international_brands", "physical_stores", "active_social"],
    evidence: ["International designer brand page", "Two showroom addresses", "Evening edit updated this month", "Premium price positioning"],
  },
  {
    id: "demo-2",
    company: "Lale Occasion House",
    website: "https://demo.example/lale-occasion",
    country: "Turkey",
    city: "Ankara",
    customerType: "Occasion Wear Retailer",
    description: "Established evening and ceremony dress retailer serving premium local customers.",
    sourceUrl: "https://demo.example/source/lale-occasion",
    signals: ["premium_positioning", "evening_dress_focus", "physical_stores", "active_social"],
    evidence: ["Dedicated evening-dress category", "Premium campaign imagery", "Physical store address"],
  },
  {
    id: "demo-3",
    company: "Anatolia Dress Group",
    website: "https://demo.example/anatolia-dress",
    country: "Turkey",
    city: "Izmir",
    customerType: "Distributor & Retailer",
    description: "Regional dress distributor supplying independent boutiques across western Turkey.",
    sourceUrl: "https://demo.example/source/anatolia-dress",
    signals: ["importer", "multi_brand", "wholesale", "international_brands", "physical_stores"],
    evidence: ["Wholesale application page", "Imported brand catalogue", "Retail partner list", "Izmir showroom"],
  },
  {
    id: "demo-4",
    company: "Nişantaşı Couture Edit",
    website: "https://demo.example/couture-edit",
    country: "Turkey",
    city: "Istanbul",
    customerType: "Designer Boutique",
    description: "Curated boutique focused on embellished couture, gala and red-carpet dressing.",
    sourceUrl: "https://demo.example/source/couture-edit",
    signals: ["multi_brand", "premium_positioning", "evening_dress_focus", "international_brands", "active_social"],
    evidence: ["Hand-beaded couture collection", "International designer mentions", "High-frequency social activity"],
  },
  {
    id: "demo-5",
    company: "Marmara Bridal & Evening",
    website: "https://demo.example/marmara-bridal",
    country: "Turkey",
    city: "Bursa",
    customerType: "Bridal & Evening Store",
    description: "Bridal-led store with a growing evening-dress department and three regional locations.",
    sourceUrl: "https://demo.example/source/marmara-bridal",
    signals: ["evening_dress_focus", "physical_stores", "active_social"],
    evidence: ["Evening department navigation", "Three store locations", "Recent occasion-wear posts"],
  },
  {
    id: "demo-6",
    company: "Golden Horn Fashion Trade",
    website: "https://demo.example/golden-horn-trade",
    country: "Turkey",
    city: "Istanbul",
    customerType: "Fashion Importer",
    description: "Fashion trading company importing premium apparel for boutique retail partners.",
    sourceUrl: "https://demo.example/source/golden-horn",
    signals: ["importer", "wholesale", "international_brands", "multi_brand"],
    evidence: ["Import and distribution statement", "Boutique partner programme", "International supplier references"],
  },
];
